export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";

export const ADMIN = "ADMIN";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const LOGOUT = "LOGOUT";

export const ACCOUNT_DELETED = "ACCOUNT_DELETED";

export const GET_DEPARTMENT = "GET_DEPARTMENT";
export const GET_DEPARTMENTS = "GET_DEPARTMENTS";
export const CLEAR_DEPARTMENT = "CLEAR_DEPARTMENT";
export const DELETE_DEPARTMENT = "DELETE_DEPARTMENT";

export const GET_SUBDEPARTMENT = "GET_SUBDEPARTMENT";
export const GET_SUBDEPARTMENTS = "GET_SUBDEPARTMENTS";
export const CLEAR_SUBDEPARTMENT = "CLEAR_SUBDEPARTMENT";
export const DELETE_SUBDEPARTMENT = "DELETE_SUBDEPARTMENT";

export const GET_EMPLOYEE = "GET_EMPLOYEE";
export const GET_EMPLOYEES = "GET_EMPLOYEES";
export const CLEAR_EMPLOYEE = "CLEAR_EMPLOYEE";
export const DELETE_EMPLOYEE = "DELETE_EMPLOYEE";

export const GET_LOGS = "GET_LOGS";
export const CLEAR_LOGS = "CLEAR_LOGS";
export const DELETE_LOG = "DELETE_LOG";
